### PR TITLE
Update NOTE to target the correct tag, not the ref

### PR DESCRIPTION
**Pull request by rhymes**

### CODE REVIEW

**Comment by Xavdidtheshadow** [comment]
@rhymes Since someone clicking that link is looking for docs, wouldn't it make sense to link them to a page that has the correct docs, instead of requiring another click to get to the readme?

**Comment by rhymes** [comment]
@Xavdidtheshadow we're linking to the same thing, the link I used it's just the explicit name of the tag 0.3.0 instead of the ref id of git

**Comment by Xavdidtheshadow** [comment]
Sure, but I figure most people will be clicking the link to find the old copy of the readme, not for the tarball. Despite being the official tag page, there's not a lot of useful info on that page 






~DB

**Comment by rhymes** [comment]
@Xavdidtheshadow click on the link I put in the patch ;-) https://github.com/adelevie/parse-ruby-client/tree/v0.3.0

maybe the wording is not correct but the page at the end of the *IS* the readme of the 0.3.0 version.

**Comment by Xavdidtheshadow** [comment]
huh. I must have clicked the wrong thing the first time, I thought the link sent to https://github.com/adelevie/parse-ruby-client/releases/tag/v0.3.0, which is a dumb place to send people.

**Pull request merged**
