### PR TITLE
Use $in syntax for channels when they are in query.

### PR DESCRIPTION
**Pull request by nashby**
fixes issue described in https://github.com/adelevie/parse-ruby-client/issues/190

### CODE REVIEW

**Comment by rhymes** [comment]
@nashby thanks for the fix, just one thing: did you test it with https://github.com/ParsePlatform/parse-server or just api.parse.com ?

Thanks

**Comment by nashby** [comment]
@rhymes I tested it with parse-server. Looks like current master branch works with api.parse.com without my fix though.

**Comment by nashby** [comment]
@rhymes I tested for both now. The fix works.

**Comment by rhymes** [comment]
@nashby thanks!

**Pull request merged**
