### PR TITLE
Ensure build with new Ruby versions

### PR DESCRIPTION
**Pull request by nicolasleger**

### CODE REVIEW

**Comment by rhymes** [comment]
I don't see the point in testing all the minor versions of a release unless there's a specific bug related to parse-ruby-client. Nor should it test for the HEAD version of the core language which is not even released yet. Don't you agree?

**Comment by nicolasleger** [comment]
@rhymes You're totally right, I'm agree. I updated the patch to auto test on `2.x` patched versions and avoid to write down the minor all time.

**Comment by rhymes** [comment]
There's a bug in the syck library apparently, that's why this patch won't build. If you look at master they've danced around it: https://github.com/adelevie/parse-ruby-client/blob/master/test/helper.rb#L30

You should probably update your patch with the latest master

**Comment by nicolasleger** [comment]
Thanks @rhymes, the patch for Syck didn't work for Ruby `2.2.0`, I fixed it.

Indeed, by specifying `2.2` Travis should test on the most patched version (the `2.2.2`) but currently Travis has not been updated to do so (see issue [travis-ci/travis-ci#3885](https://github.com/travis-ci/travis-ci/issues/3885)) so it tests on `2.2.0` which wasn't working properly.

**Comment by rhymes** [comment]
Great!

**Pull request merged**
