### PR TITLE
Remove singleton

### PR DESCRIPTION
**Pull request by rhymes**
I think that after a year of a half since #165 it is time to start cleaning up the code and remove the singleton object for good.

### CODE REVIEW

**Comment by rhymes** [comment]
@xavdid what do think about this PR?

**Comment by xavdid** [comment]
It's probably fine but also I don't know how I feel about doing this without any releases. Hopefully people aren't pointing their gemfiles at the master branch's head, but without any proper releases I'm nervous we break stuff. 

There's credence to just pulling off the bandaid, making the breaking changes, and cutting a release.

**Comment by rhymes** [comment]
@xavdid I understand your point but it has been in the master branch more than a year and the latest release is from July 2014... This doesn't completely justify breaking the compatibility but it's also a change long time coming, the owner of the project has abandoned it and we've said times and times again we were going to remove the singleton. 

If we hold off on this and finally release a 1.0 in the coming weeks/months (hopefully) we are not going to be able to remove it until the next major release which might come in another year or something (if the singleton is there people will keep on using it :))

Also, removing the singleton is also the first step in a code cleanup I'd like to do before we cut 1.0

**Comment by xavdid** [comment]
Yeah, makes sense! I've added a blurb to the readme so that people can easily fix builds we may break doing this. Otherwise let's do it!

**Pull request merged**
