### PR TITLE
Added Keys query operator

### PR DESCRIPTION
**Pull request by Xavdidtheshadow**
Per https://parse.com/docs/rest#queries-constraints, queries can now ask for only certain fields. Added relevant test, tidied up the .gitignore and added example to readme.

### CODE REVIEW

**Comment by Xavdidtheshadow** [comment]
Also changed readme badges to use [shields.io](https://github.com/badges/shields) which makes them nice and pretty.

**Comment by Xavdidtheshadow** [comment]
woohoo! `quiet` and `.keys` are in master.

**Comment by rhymes** [comment]
@Xavdidtheshadow did you check if the cassette is still valid after a year :) ?

**Comment by rhymes** [comment]
Sorry, I just noticed you updated it. Thanks!

**Pull request merged**
