### PR TITLE
Improve Parse::Client: handle more errors and expose more Faraday options so we can change it easily

### PR DESCRIPTION
**Pull request by kidlab**
**What is this PR for?**
We are using `parse-ruby-client` on our production and experiencing a lot of errors like these:
* Faraday::TimeoutError: execution expired
* Faraday::ConnectionFailed: Connection reset by peer - SSL_connect
* Faraday::TimeoutError: Net::ReadTimeout

After inspecting the code, we found out that there is no way to change the `timeout` but the monkey patch, because we hard-code it!
Another reason is sometimes the retry does not work with some error like `Faraday::ConnectionFailed`. We don't think it is the SSL problem, because we checked our server's certificates, and it's okay.

After we applied this patch, and adjusted the `timeout` and `backoff_factor` options, the error rate was significantly reduced.

Any comments is appreciated!

### CODE REVIEW

**Comment by rhymes** [comment]
@kidlab thank you very much! The only thing I'm not sure about is having SSLError in the list of exceptions to retry for.

**Comment by Xavdidtheshadow** [comment]
Yeah, typically a SSL error is a configuration issue, so retrying doesn't get you anywhere. Pull that out and I'm good to merge!

**Comment by kidlab** [comment]
Yeah, I know it's strange, but we did get a lot of error like that on our production, and I'm sure that it does not relate to SSL configuration, because our servers are production ready. It happens when there are many requests in a short period, I think it's Parse server's throttle to protect itself.

Anyway, I think we should also parameterize handled exceptions, so that people can add more custom exception if they want.

**Comment by Xavdidtheshadow** [comment]
Interesting. In that case it might be worth surfacing the error itself or a matching custom error so you can decide how to handle it in the application layer rather than potentially misleading people who actually do have ssl issues 






~DB

**Comment by kidlab** [comment]
Agree. I updated the pull request, please check it out.

**Pull request merged**
