### PR TITLE
[Push Notification] Added support for no channels

### PR DESCRIPTION
**Pull request by fabiomassimo**
## Push Notification:
- If there are no channels (default no channel), the push notification
is sent to all target devices. (issue [#140](https://github.com/adelevie/parse-ruby-client/issues/140))
- Improved support for targeting by platform: a device type is specified as [`where`
clause](https://www.parse.com/docs/push_guide#options-platform/REST)
- Improved support for advanced targeting: if a channel is specified it's also possible to use `where` clause in it.

### CODE REVIEW

**Comment by Xavdidtheshadow** [comment]
@fabiomassimo hey, we can't auto merge this anymore because of other changes. If you'd like to get this in, could you merge master back into your branch and push that?

**Comment by rhymes** [comment]
@Xavdidtheshadow not sure what problem this PR solves.

**Comment by koenpunt** [comment]
@rhymes see #140

**Comment by rhymes** [comment]
@koenpunt thanks!

**Comment by fabiomassimo** [comment]
@Xavdidtheshadow thanks for taking care of this pr. Is there something else I can do to help you out?

**Comment by rhymes** [comment]
@fabiomassimo thanks for the fix! You just need to update your branch with the current master and fix the conflicts so that your PR can be merged. 

See https://help.github.com/articles/syncing-a-fork/

**Comment by fabiomassimo** [comment]
I just merged the latest changes from current master branch but I didn't come across any merge conflict. Am I missing something?

**Comment by Xavdidtheshadow** [comment]
Did you checkout and git pull each branch before merging?






~DB

**Comment by fabiomassimo** [comment]
I merged *only* from current `master` branch (main repo).
Why should I merge *all* branches?

**Comment by Xavdidtheshadow** [comment]
Sorry, wasn't clear. I meant pulled current master and merged that. Sometimes people forget to pull and then merge without conflict. But not that though, huh?




I'm on mobile now, but I can actually dig into what the conflicts are later if you haven't found them by then. 






~DB

**Comment by fabiomassimo** [comment]
@Xavdidtheshadow thanks! I didn't encounter any conflict indeed. Let me know if I'm missing something. It seems good for me..

**Comment by Xavdidtheshadow** [comment]
@fabiomassimo nice, the conflict seems to have resolved itself. Merged!

**Comment by rhymes** [comment]
@Xavdidtheshadow just a thought, with my push and this we should probably start improving the documentation because they are both changes that modify the behavior

**Comment by Xavdidtheshadow** [comment]
@rhymes totally agree. Do you mind adding relevant documentation as part of #167?

**Comment by rhymes** [comment]
@Xavdidtheshadow done

**Pull request merged**
