### PR TITLE
No parse com

### PR DESCRIPTION
**Pull request by rhymes**
This branch makes the following changes:

- application_id is the only required key (see https://parseplatform.github.io/docs/parse-server/guide/#keys)
- all the other keys are still optional
- host does not have a default anymore
- path still defaults to '/1' (should we change it to '/parse' ?)

Refs #217

### CODE REVIEW

**Comment by xavdid** [comment]
I like `/parse` as the default for the path since that's the default given in their docs. 

Do we want to throw an error if `:host` ins't provided or will the error from Faraday for passing it a `nil` host be enough?

**Comment by rhymes** [comment]
@xavdid I agree with changing the default to /parse, we should just adhere to Parse Server. I'll update the PR

I'm not sure about throwing an error, because we don't do it for other required params, like application_id - I would leave it as is for now, we can maybe open a separate issue and think about it after I've done some cleanup.

**Comment by xavdid** [comment]
Also why does coveralls test each commit 4 times?

**Comment by rhymes** [comment]
@xavdid don't know. another thing to look into :-)

+1 for the merge?

**Comment by xavdid** [comment]
LGTM!

**Pull request merged**
